# Generated by Django 5.2.7 on 2025-11-10 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExcelData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('column1', models.CharField(blank=True, max_length=200, null=True)),
                ('column2', models.CharField(blank=True, max_length=200, null=True)),
                ('column3', models.TextField(blank=True, null=True)),
                ('column4', models.IntegerField(blank=True, null=True)),
                ('column5', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('column6', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Excel Data',
                'verbose_name_plural': 'Excel Data Records',
                'db_table': 'excel_data',
                'ordering': ['-created_at'],
            },
        ),
    ]
